# Generated by Django 3.0.5 on 2020-04-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
