[project]
name = "django_views_tutorial"
version = "0.1.2"
description = "Function and class-based Django view repository."
requires-python = ">=3.12,<4.0"
authors = [{name = "Todd Birchard", email = "todd@hackersandslackers.com"}]
maintainers = [{name = "Todd Birchard", email = "todd@hackersandslackers.com"}]
license = "MIT"
readme = "README.md"
keywords = ["Django", "Django Views", "MVC", "Frameworks", "Tutorial"]
scripts = {run = "django_views_tutorial.wsgi:application"}
dependencies= [
    "django>=3.0.0,<5.0.0",
    "python-dotenv>=1.1.0",
    "mysqlclient>=2.2.7",
    "django-environ>=0.12.0",
    "gunicorn>=23.0.0",
    "black>=25.1.0",
    "isort>=6.0.1",
    "flake8>=7.2.0",
    "pylint>=3.3.7",
    "pytest>=8.3.5",
    "coverage>=7.8.0",
    "mypy>=1.15.0"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.'MESSAGES CONTROL']
disable = "C0103,C0301,W0703,W0621"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = "120"
