# Generated by Django 3.0.5 on 2020-04-04 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 8, 37, 32, 851790)),
        ),
        migrations.AlterField(
            model_name='guestmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 8, 37, 32, 851498)),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
