# Generated by Django 3.0.5 on 2020-04-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_views', '0002_auto_20200420_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
