# Generated by Django 3.0.5 on 2020-04-05 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_views', '0002_auto_20200404_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 19, 5, 46, 952178)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 19, 5, 46, 951910)),
        ),
    ]
