# Generated by Django 3.0.5 on 2020-04-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("function_views", "0004_auto_20200421_1657"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="facebook_profile",
        ),
    ]
