# Generated by Django 3.0.5 on 2020-04-04 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('simpleviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 3, 1, 0, 312884)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 3, 1, 0, 312536)),
        ),
    ]
